version: "3"

services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"