name: Docker Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 16.171.236.68
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/my-portfolio
            
            # Pull latest code
            git reset --hard
            git pull origin main

            # Stop old container
            docker stop my-portfolio-container || true
            docker rm my-portfolio-container || true

            # Rebuild image
            docker build -t my-portfolio .

            # Run new container
            docker run -d -p 80:80 --name my-portfolio-container my-portfolio